name: Deploy Enterprise App

on:
  push:
    branches:
      - main

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/enterprise-app:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/enterprise-app:prod-${{ github.sha }}

      - name: Deploy to production server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USER }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/enterprise-app:latest
            docker stop enterprise-app-prod || true
            docker rm enterprise-app-prod || true
            docker run -d \
              --name enterprise-app-prod \
              --restart unless-stopped \
              -p 4200:80 \
              ${{ secrets.DOCKER_HUB_USERNAME }}/enterprise-app:latest
